### PR TITLE
[README] Add link to TSLint rules for RxJS

### PR DESCRIPTION
**Pull request by HideDev**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [ ] New feature, bugfix, or enhancement
- [ ] Includes tests
- [x] Documentation update

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @HideDev! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by HideDev** [comment]
screen shot 2017-12-21 at 03 57 32

**Comment by adidahiya** [comment]
@HideDev that web page might've been undergoing maintenance at the time -- can you try the CLA again?

**Comment by HideDev** [comment]
contributor license agreement palantir

**Comment by HideDev** [comment]
@adidahiya maybe I will create a new pull request?(CLA required still pending)

**Comment by ajafff** [comment]
Reopening the PR worked. Thanks @HideDev

**Pull request merged**
