### PR TITLE
Add fix for no-unused-variable, only for imports

### PR DESCRIPTION
**Pull request by alexeagle**
cc @chuckjaz

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @alexeagle! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by alexeagle** [comment]
cc @ScottSWu too - we talked about this one a couple times

**Comment by alexeagle** [comment]
cc @paulvanbrenk I think this handles more cases than https://github.com/Microsoft/TypeScript/blob/pvb/discoverCodeActions/src/services/codefixes/unusedIdentifierFixes.ts
is that up-to-date? Where do we want to land this feature? I don't think tslint and typescript need two independent implementations...

**Comment by alexeagle** [comment]
Ping!

**Comment by alexeagle** [comment]
Note, my fix for #1569 is based on this one

**Pull request merged**
