### PR TITLE
Add auto-fixes for trailing-comma

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @alexeagle! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by alexeagle** [comment]
CLA: the commit is authored with my @google.com address, which is corporate signed.

**Comment by JKillian** [comment]
Thanks @alexeagle, this'll be a useful auto-fix. Are you aware of @markwongsk's PR, #1486, to make sure that the trailing-comma rule is applied evenly everywhere? Might be worth basing this branch off of his - hope it isn't too much additional work

**Comment by alexeagle** [comment]
That rebase looks easy, no worries. I just copy-paste the .lint file and do
whatever the ~~~ says, then delete it :)

**Comment by markwongsk** [comment]
Hey @alexeagle I updated my PR to be based off master and to point at master. You should be able to rebase now :)

**Comment by alexeagle** [comment]
thanks, rebased now, PTAL @JKillian

**Comment by JKillian** [comment]
Thanks!

**Pull request merged**
