### PR TITLE
[new-rule] add whitespace rule for open braces

### PR DESCRIPTION
**Pull request by erikseulean**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [x] Documentation update

#### Overview of change:
Implements a whitespace option `check-postbrace` that is checking for a space, new line or tab after an open curly brace.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @erikseulean! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by JKillian** [comment]
Hi @erikseulean, please see https://cla.palantir.com/, thanks!

**Comment by erikseulean** [comment]
@JKillian I cannot find any terms there, it's only an authorization link for individual contributors but nothing rearding the content of the CLA.

**Comment by JKillian** [comment]
Hi @erikseulean, turns out you have to authorize Github first before you can see the document. Obviously this isn't ideal, so I've pasted some screenshots of the document below so you can see it ahead of time:

image
image
image

**Comment by erikseulean** [comment]
Hi @JKillian thanks for this.

**Comment by erikseulean** [comment]
ping @JKillian Anybody up to look over this?

**Comment by erikseulean** [comment]
@johnwiseheart do you think this brings some value to the existing codebase ? I'm happy to have this closed in case you don't consider it valuable to remove the clutter of long standing PRs.

**Comment by johnwiseheart** [comment]
I think this added feature is worth having - does your addition also work with `--fix`? If so, it would be good to write a test for that.

**Comment by erikseulean** [comment]
Hmm, not sure I understand exactly what test you want me to add. Could you please point me to a similar example ? I have already added a test, and a test fix, is it something else you asked me about or you missed those ?

**Comment by johnwiseheart** [comment]
My mistake - I missed your `fix` test when reviewing. Thanks for your contribution!

**Comment by Jameskmonger** [comment]
When will this be published @johnwiseheart?

**Comment by johnwiseheart** [comment]
I will try and make a new release next week.

**Pull request merged**
