### PR TITLE
Require semicolon for type alias

### PR DESCRIPTION
**Pull request by andy-ms**
Redo of #1475

### CODE REVIEW

**Comment by JKillian** [comment]
Thanks! 👍  for merging this when 4.0 time comes

**Comment by JKillian** [comment]
Sorry, think I introduced conflicts here when I merged your other PR. Mind merging develop into this one and repushing?

**Comment by andy-ms** [comment]
`grunt mochaTest:test` works on my machine. Looks like it's timed out in CI.

**Comment by JKillian** [comment]
All looks good to me, thanks @andy-ms

**Pull request merged**
