### PR TITLE
Feature: Introduce new rule: newline-before-throw

### PR DESCRIPTION
**Pull request by ovr**
Hey!

#### PR checklist

- [ ] Addresses an existing issue: #0000
- [X] New feature
  - [X] Includes tests
- [ ] Documentation update

#### Overview of change:

New rule 😸 

#### CHANGELOG.md entry:

[new-rule] `newline-before-throw`

Thanks

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @ovr! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by ericanderson** [comment]
I do not think that the job of tslint is to enforce code formatting standards and am personally questioning if any such rules should exist as the core part of tslint. There is likely a need for a tslint-contrib that is more openly/publicly maintained. 

I'm going to hold this PR for a bit while we figure out a written policy for which types of rules will be a part of tslint out of the box.

**Comment by ovr** [comment]
> I do not think that the job of tslint is to enforce code formatting standards and am personally questioning if any such rules should exist as the core part of tslint. 

TSLint is an extensible static analysis tool that checks TypeScript code for readability, maintainability, and functionality errors.

**Comment by VincentLanglet** [comment]
This rules seems as logic as the "newline before return" rules already implemented.

And as a typescript user, I expect from tslint to check as good my `ts` code that eslint do for my `js`.
This rules exist in the core part of `eslint` so why not `tslint` ?

**Comment by VincentLanglet** [comment]
@ericanderson @JoshuaKGoldberg @adidahiya Some months since the PR is created and ready to merge.

This is labelled as "In discussion", can we help about it ?

**Comment by adidahiya** [comment]
@VincentLanglet @ovr sorry for the delay here, but as per #4534 and #3592, I am inclined to close this PR and avoid adding _new_ formatting rules to core TSLint. This new rule can happily live in a community rule set outside of this repo.

**Pull request closed without merging**
