### PR TITLE
Remove comment-type

### PR DESCRIPTION
**Pull request by smhmayboudi**
Could not find implementations for the following rules specified in the configuration:
    comment-type
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.

#### PR checklist

- [X] New feature, bugfix, or enhancement

#### CHANGELOG.md entry:
[bugfix] `comment-type` is removed from config/all.ts

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @smhmayboudi! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by giladgray** [comment]
@smhmayboudi this PR does not seem correct. `comment-type` was added very recently in #4008 and has not been shipped yet. 

how did you get this error? with an installed `tslint` package or when building from source?

**Comment by smhmayboudi** [comment]
I got from `tslint` package due to customize my rules. I check the `all.ts` from git source and put `comment-type` to my rules.

**Comment by johnwiseheart** [comment]
If you installed tslint using a package manager, the version of the package that you are using is older than latest master on github. It's not possible to use rules that only exist on master but have not been released in the released version of `tslint`.

**Comment by johnwiseheart** [comment]
Closing since I don't think this is an issue

**Pull request closed without merging**
