### PR TITLE
Pass configFile to TypeScript to prevent sensitivity to current working directory

### PR DESCRIPTION
**Pull request by voidqk**
The `tslint` program will not output the same results when ran from a different working directory, despite having `--project` and `--config` set correctly.

This is due to not passing the location of the `configFile` to TypeScript, which causes TypeScript to use the current working directory as a default.

This PR simply passes the file in the right location, allowing TypeScript to figure out the working directory from there.

#### PR checklist

- [ ] Addresses an existing issue: #0000
- [x] Bugfix
  - [ ] Includes tests
- [ ] Documentation update

#### Overview of change:

Passes the `configFile` variable to TypeScript, instead of leaving it as `undefined`.

#### CHANGELOG.md entry:

[bugfix] Remove sensitivity to current working directory

### CODE REVIEW

**Comment by voidqk** [comment]
great question -- it was like that when I got here ¯\_(ツ)_/¯

**Comment by giladgray** [comment]
@voidqk please merge latest `master` and try to fix any remaining failed tests. 
we cannot merge until ✅

**Comment by voidqk** [comment]
fixed the lint errors and merged with upstream... still have four tests failing, don't have the time to look into it right this moment

**Comment by suchanlee** [comment]
sounds fine, just ping us when the build is fixed so we can review!

**Comment by JoshuaKGoldberg** [comment]
Agh. @voidqk in attempting to rebase this branch I reset your master to the upstream's, which caused GitHub to close the PR, which I didn't realize would block me from pushing to your branch again. Would you mind re-pushing d8aa5d8466f1f01d3ee42d62a70f336b423c0b72? It's good to go; the issues with Prettier formatting not being applied to all files have been resolved.

_(I could send this as a separate PR but figured it'd be nice for your account to have credit 🚀)_

**Comment by JoshuaKGoldberg** [comment]
By the way, it's generally a good idea to _not_ send pull requests from a forked `master` branch. `master` is what you want to try to keep in sync with upstream changes whenever possible. Instead, it'd be more reliable (less prone to shenanigans) to use individual branches per pull request.

**Comment by voidqk** [comment]
cool thanks -- I don't mind if you apply the fix yourself, it's just a single line change... otherwise I can try to re-push tomorrow

**Pull request closed without merging**
