### PR TITLE
Fix error location for typedef rule (#968)

### PR DESCRIPTION
**Pull request by fhemery**
#### PR checklist

- [x] Addresses an existing issue: #968
- [x] New feature, bugfix, or enhancement
- [x] Includes tests
- [ ] Documentation update - N/A

#### What changes did you make?

I modified the typedef rule so that error location is adjusted, and updated the tests accordingly.

#### Is there anything you'd like reviewers to focus on?

I have chosen to modify as well the behaviour for the arrow operator and the function calls, in an attempt to be homogeneous. I think you should have a close look at this behaviour change in particular. Feel free to reject the PR if behaviour is not correct, I'll patch it.
Please note that this is my first contribution to open source, so any comment is welcome !

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @fhemery! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by adidahiya** [comment]
@fhemery thanks for taking the time to make this contribution!

I don't think we should accept this change, however. The original error location for this rule was intentional because it pointed to the place where you add a typedef (e.g. the location of the `:` in a `: boolean`) typedef. Why do you want to change it?

**Comment by fhemery** [comment]
Your comment on the 12th of February says that the variable itself should be highlighted. So there are three options from my point of view :
* I misinterpreted it totally, and I should highlight the whole variable instead of the beginning of the variable only
* I did it correctly for the variables, but shouldn't have made the change for the function calls, in which case I can amend the commit to remove the function part
* The behaviour is no longer needed, and I should try another bug (any suggestion ?)

Could you let me know which option is correct ? 
Thanks in advance,
Frederic

**Comment by nchen63** [comment]
@fhemery I don't think you misinterpreted the original issue. 

If you updated the fix to include the entire name of the variable/function/destructuring object we'd accept the PR. Also, could you change the error to say "type definition" instead of "typedef"?

**Comment by nchen63** [comment]
@fhemery also, please run `npm run verify` to make sure your project lints and runs tests

**Comment by adidahiya** [comment]
sorry, this PR is stale. please open a new one if you wish to pursue this change.

**Pull request closed without merging**
