### PR TITLE
[new-fixer]: Add space before comment message fixer

### PR DESCRIPTION
**Pull request by tanniiz**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [ ] Documentation update

#### Overview of change:
- Add fixer for check-space option in comment-format rule

#### CHANGELOG.md entry:
[new-fixer] `comment-format`

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @tanniiz! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by suchanlee** [comment]
Can we add some tests?

**Comment by suchanlee** [comment]
@tanniiz happy to merge this once there are tests

**Comment by tanniiz** [comment]
Hi All,

I have added space-before-comment tests ;)

Thanks,
Tan

**Pull request merged**
