### PR TITLE
Add "ban-types" to `tslint:latest`.

### PR DESCRIPTION
**Pull request by andy-ms**
#### PR checklist

- [X] Addresses an existing issue: #1844
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Overview of change:

Added a default setting for `ban-types`. This is the same as the `forbidden-types` rule used to do in `types-publisher`.

#### CHANGELOG.md entry:

[enhancement] Add "ban-types" to `tslint:latest`.

### CODE REVIEW

**Comment by adidahiya** [comment]
Looks like there are some lint failures in the build @andy-ms

**Comment by nchen63** [comment]
are the changes to package.json needed?

**Comment by andy-ms** [comment]
I added a `.d.ts` file in a lint rule, which was being linted. Can't make it a `.test.ts` file, and that seemed unnecessary if we can ignore the entire directory.

**Comment by nchen63** [comment]
@andy-ms thanks!

**Pull request merged**
