### PR TITLE
Rewrite and bugfix no-switch-case-fallthrough

### PR DESCRIPTION
**Pull request by ajafff**
#### PR checklist

- [x] Fixes: #785, #950, #1033, #1538
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests

#### What changes did you make?

[bugfix] handle break, throw, continue and return nested in block, if-else and switch
[bugfix] allow empty case clauses before default clause
[enhancement] allow single line comment `// falls through`

#### Is there anything you'd like reviewers to focus on?

Depends on #2217

### CODE REVIEW

**Comment by nchen63** [comment]
@ajafff thanks!

**Comment by ajafff** [comment]
Github didn't automatically closed the other open issues mentioned above: #950, #1033, #1538

**Comment by glen-84** [comment]
The `// falls through` comment check should probably be case-insensitive and allow additional text.

* `// falls through`
* `// Falls through`
* `// Falls through.`
* `// Falls through -- for reasons.`

**Comment by ajafff** [comment]
@glen-84 makes sense. I opened #2983 to address this.

**Pull request merged**
