### PR TITLE
Indent rule option to allow spaces after tabs

### LINKED ISSUE #1306: More lenient "indent": [true, "tabs"]
Consider the following formatting where `~~~>` is a tab and `-` is a space:

```typescript
~~~>if-(longArgumentlongArgumentlongArgument
~~~>---&& anotherLongArgumentanotherLongArgument) {
~~~>~~~>// ...
~~~>}
```

This gets flagged by the indent rule.

Would you be up for me adding an option to allow <4 spaces at the end of the tabs?

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Allows a configurable maximum number of spaces after tabs.

Fixes #1306.

### CODE REVIEW

**Comment by JKillian** [comment]
(Feeling a little hesitant)[https://github.com/palantir/tslint/issues/1306#issuecomment-227623464] on this, let's see what others think before going further. Worst case you can always make this a custom rule if needed in some of your projects

**Comment by olegstepura** [comment]
IMHO one should make a choice and never mix spaces with tabs.

**Comment by chrismbarr** [comment]
Yeah I agree, I can't see a lot of people needing a rule to enforce tabs only, but also sometime allow a maximum of 3 spaces after that.  Perhaps that makes sense for your team, but I cannot think of a good use case for that option.

Typically the choices are "tabs", "spaces", or "I don't care to enable this rule"

**Comment by JoshuaKGoldberg** [comment]
@chrismbarr I've put a defense + use case in the other thread, https://github.com/palantir/tslint/issues/1306#issuecomment-227795888

**Comment by JKillian** [comment]
I understand where you're coming form @JoshuaKGoldberg, but mixing tabs and spaces doesn't seem like an idea we want to encourage, so I'm going to close this. I never enjoy closing PRs that people have put time and effort into, but in this case it seems like the best course of action.

**Comment by JoshuaKGoldberg** [comment]
Makes sense, no worries! I appreciate you & the other participants taking the time to think it over and give feedback.

**Comment by vhakulinen** [comment]
I'll leave my (and probably my colleague's) two cents here and vouch for this opt-in feature. I can really relate to this comment: https://github.com/palantir/tslint/issues/1306#issuecomment-227795888 (already mentioned above by @JoshuaKGoldberg). _Really_ useful when you're using tabs for indention but still want to line up arguments or conditions in if statement with the line above (after indention tabs).

**Pull request closed without merging**
