### PR TITLE
Compile tests before runing tests

### PR DESCRIPTION
**Pull request by mohsen1**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### What changes did you make?

Running `npm test` does not reflect changes in test, this will make sure we're always compiling tests before running them. 

#### Is there anything you'd like reviewers to focus on?

(optional)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @mohsen1! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by nchen63** [comment]
why can't you just run `compile:test`?

**Comment by mohsen1** [comment]
`pretest` is triggered automatically by npm when running `npm t`. [docs](https://docs.npmjs.com/misc/scripts)

**Comment by adidahiya** [comment]
Oh, right, I forgot about that. Then it probably makes sense to refactor the existing `npm run test:pre` script?

**Comment by mohsen1** [comment]
@adidahiya that makes sense. native npm scripts pre stuff is better.

I noticed that this change will not do it for when you make changes in source code itself. It should compile source and test.

In other note, why did you guys decide to compile tests and source instead of using `ts-node/register`?

**Comment by nchen63** [comment]
what benefit would there be to use `ts-node/register`? It still needs to compile

**Comment by mohsen1** [comment]
@nchen63 you don't need to compile before test and in watch mode it's pretty fast due to TS compiler caching

**Comment by nchen63** [comment]
I looked at the `ts-node` source, and it doesn't seem to involve watching. For it to be in watch mode, it would also need to keep the process alive, right?

**Comment by mohsen1** [comment]
I used it with webpack and watch was really fast. Maybe it's the webpack...

**Comment by nchen63** [comment]
Yeah probably WebPack.

**Pull request closed without merging**
