### PR TITLE
no-unnecessary-type-assertion: Don't check `!` if --strictNullChecks is not enabled

### PR DESCRIPTION
**Pull request by andy-ms**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [X] New feature, bugfix, or enhancement
  - [X] Includes tests
- [ ] Documentation update

#### Overview of change:

Doesn't check whether `x!` is an unnecessary non-null assertion if `--strictNullChecks` is not enabled.

#### CHANGELOG.md entry:

[bugfix] no-unnecessary-type-assertion: Don't check `x!` non-null assertions if `--strictNullChecks` is not enabled

### CODE REVIEW

**Comment by ajafff** [comment]
@andy-ms what's the motivation for this change? Adding assertions during migration to `--strictNullChecks`?

**Comment by andy-ms** [comment]
With `--strictNullChecks` on this change is unnecessary. But without `--strictNullChecks`, the rule currently produces a lot of false positives at `x!` because it gets a non-null type for `x`.

**Comment by ajafff** [comment]
Yeah, I get that. But what's the use case?
There's no reason to use non null assertions without strictNullChecks. The assertion is really unnecessary. 
It only makes sense if you are migrating to strictNullChecks.

**Comment by andy-ms** [comment]
At least for TypeScript, we annotated our code as best as we could even without having `--strictNullChecks` enabled. I wouldn't want to have to remove all of those assertions to enable this lint rule, then have to add them all back when enabling `--strictNullChecks`.

**Comment by giladgray** [comment]
@andy-ms this change looks good! would you mind merging latest `master` and resolving merge conflicts?

**Comment by JoshuaKGoldberg** [comment]
👋 @andy-ms and @NaridaL! I don't know if this is still relevant or useful to you, but heads up that this is now merged in and will be available in the next TSLint release. Sorry this took so long!

**Pull request merged**
