### PR TITLE
Reduce false positive rate in no-invalid-template-strings

### PR DESCRIPTION
**Pull request by mitchellwills**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [ ] Documentation update

#### Overview of change:

* Don't flag unmatched ${ in a regular string
* Also flag the entire expression, not just the opening brace

#### CHANGELOG.md entry:

[enhancement] Don't flag unmatched ${ in no-invalid-template-strings

### CODE REVIEW

**Comment by mitchellwills** [comment]
Any thoughts on this? The testNext failure looks unrelated to this change.

**Comment by mitchellwills** [comment]
Looks like the build is still failing. Still appears unrelated to this PR

**Comment by mitchellwills** [comment]
Any thoughts on this?

**Comment by mitchellwills** [comment]
@johnwiseheart looks like all the tests are passing now

**Comment by johnwiseheart** [comment]
Thanks for your contribution!

**Pull request merged**
