### PR TITLE
[docs] additional code examples for 12 rules

### PR DESCRIPTION
**Pull request by Shinigami92**
#### PR checklist

- [x] Addresses an existing issue: #3601
- [x] New feature, bugfix, or **enhancement**
  - [ ] Includes tests
- [x] Documentation update

#### Overview of change:

Added code examples to rules:

- noAny
- noEmptyInterface
- noSparseArrays
- noUnnecessaryCallbackWrapper
- objectLiteralSortKeys
- oneVariablePerDeclaration
- onlyArrowFunctions
- preferTemplate
- radix
- switchDefault
- typedef
- useIsnan

#### CHANGELOG.md entry:

See: "Overview of change"

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @Shinigami92! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by Shinigami92** [comment]
@palantitrech Sorry, but currently I am not allowed to sign the CLA.
I want to and will do this in the next few days / weeks.
Currently, the organization I work for joins an OSB alliance and I have to wait :/

**Comment by suchanlee** [comment]
@Shinigami92 is the CLA signed? would love to merge this!

**Comment by Shinigami92** [comment]
@suchanlee sorry but I want this too and also work on tslint
But I have to wait at my business :(
My chef said that it is in final stage and i'm hoping and praying that it's next week
This week i'm in holiday

**Comment by suchanlee** [comment]
ah okay sounds good, just let us know!

**Comment by Shinigami92** [comment]
Finally I could accept the CLA

**Comment by Shinigami92** [comment]
AFAICT everything is now ready for review and merge.
Shall I change the dates in each src/rules/code-examples/* on line 3 or are they good as is?

**Comment by johnwiseheart** [comment]
Hi! Sorry that this has been left for a while. Please update the dates of the copyrights, and then we can merge this in.

**Comment by Shinigami92** [comment]
I think in `src/rules/classNameRule.ts` an `import` line was added
that caused the conflict

**Comment by Shinigami92** [comment]
@johnwiseheart anything needed before review?

**Comment by johnwiseheart** [comment]
Looks good to me. Can you confirm whether you have signed the CLA? The cla bot seems to be a little funky right now.

**Comment by Shinigami92** [comment]
yes I have

**Comment by johnwiseheart** [comment]
Sweet, let me look into why its not reporting properly and I'll merge it in once it passes.

**Comment by Shinigami92** [comment]
yay it passed

**Comment by johnwiseheart** [comment]
Thanks for your contribution!

**Comment by Shinigami92** [comment]
I will look into some more code examples in the next few days
and then do this in a new pr

**Pull request merged**
