### PR TITLE
Update appveyor and travis to use node 4.2

### LINKED ISSUE #730: Switch node 4.1 => 4.2 in CI
according to https://github.com/nodejs/node/issues/3000#issuecomment-144894835, 4.2 will be the LTS release

### PR DESCRIPTION
**Pull request by xt0rted**
closes #730

### CODE REVIEW

**Comment by xt0rted** [comment]
It looks like appveyor hasn't updated their VMs with 4.2 yet

**Comment by xt0rted** [comment]
Since node 4.2.1 has been released should that be used or do you want to stick with 4.2.0?

**Comment by adidahiya** [comment]
I think "4.2" will make travis pick the latest 4.2.x version

**Comment by xt0rted** [comment]
Looks like AppVeyor and Travis both used `4.2.x` so this should be good now

**Comment by adidahiya** [comment]
cool thanks

**Pull request merged**
