### PR TITLE
updated package.json

### PR DESCRIPTION
**Pull request by EsrefDurna**
updated package tsutils from 2.3.0 to 2.4.0
 Npm link :  https://www.npmjs.com/package/tsutils
 Repository link : https://github.com/ajafff/tsutils/releases

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @EsrefDurna! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by EsrefDurna** [comment]
fyi cla signed

**Comment by adidahiya** [comment]
why do we need this? I'd rather upgrade tsutils when we need one of its newer features or if an automated tool like Greenkeeper made this PR.

also, when updating dependencies, we need to update the yarn.lock file as well.

**Comment by EsrefDurna** [comment]
Ok

**Pull request closed without merging**
