### PR TITLE
Don't enforce trailing spaces on newlines in typedef-whitespace rule

### LINKED ISSUE #1354: Don't enforce trailing spaces on newlines (typedef-whitespace)
### Bug Report

- __TSLint version__: `3.12.1`
- __TypeScript version__: `1.9.0-dev.20160610-1.0`
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
public aVeryLongFunctionThatExceeds100Characters(parameter1: string, parameter2: string):
    TheReturnType {
  ...
}
```

with `tslint.json` configuration:

```json
"rules": {
    "no-trailing-whitespace": true,
    "max-line-length": [ true, 100 ],
    "typedef-whitespace": [
      true,
      {},
      { "call-signature": "space" }
    ],
}
```

#### Actual behavior

When there is no space after the colon:

> expected space after colon in call-signature

When there is a space after the colon:

> trailing whitespace

#### Expected behavior

The errors are unexpected. Line breaks should be excluded from the whitespace-checking.
Although the checks do what they need to (check for a whitespaces) it is unexpected behavior.

This is opinionated so I would like to know if someone has another view on the matter or has a situation where whitespaces and newlines are useful.

### PR DESCRIPTION
**Pull request by SteveVanOpstal**
Closes #1354

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @SteveVanOpstal! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by JKillian** [comment]
@SteveVanOpstal Just curious, does this fix https://github.com/palantir/tslint/issues/1521 as well?

**Comment by SteveVanOpstal** [comment]
Yes, the example he provides is basically the same as this test: https://github.com/SteveVanOpstal/tslint/blob/3bae5b9309b3485f0e87abe456f40627a2d1ae16/test/rules/typedef-whitespace/both/onespace/test.ts.lint#L347

**Comment by JKillian** [comment]
Looks good, thanks @SteveVanOpstal!

**Pull request merged**
