### PR TITLE
Add quotes around example option

### PR DESCRIPTION
**Pull request by vgrigoriu**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [ ] New feature, bugfix, or enhancement
- [ ] Includes tests
- [x] Documentation update
- [ ] Enable CircleCI for your fork (https://circleci.com/add-projects)

#### What changes did you make?

Fix example configuration

#### Is there anything you'd like reviewers to focus on?

(optional)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @vgrigoriu! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by nchen63** [comment]
`index.html` is generated. Can you edit `arrowParenRule.ts`, line 38?

**Comment by vgrigoriu** [comment]
Here you go.

**Comment by nchen63** [comment]
@vgrigoriu thanks!

**Pull request merged**
