### PR TITLE
Prepare release 5.7.0

### PR DESCRIPTION
**Pull request by ajafff**
Should probably wait for #3163 and #3164

@adidahiya You create the version tag and github release when merging?

### CODE REVIEW

**Comment by adidahiya** [comment]
merged those PRs; can you update this one now?
yeah I can cut a release later today

**Comment by ajafff** [comment]
Merged master and updated changelog

**Comment by DevVersion** [comment]
@adidahiya Thanks. This is awesome! 
<sub>Just looks like the release is not published on NPM, while the docs and everything are already pointing to `5.7.0`.</sub>

**Comment by adidahiya** [comment]
@DevVersion I published it a few minutes ago. It's on NPM now https://www.npmjs.com/package/tslint

**Pull request merged**
