### PR TITLE
Use CircleCi 2.0

### PR DESCRIPTION
**Pull request by ajafff**
Use CircleCI 2.0

Only build once and use the result to lint and test in separate jobs. That cuts the total time taken by CI in half.

We can now add an arbitrary amount of test jobs. I decided to stick with 4 for now:
* node 4.8 with typescript@2.1
* node 6.10 with typescript@2.4
* node 8.x with typescript@stable (current version in yarn.lock)
* node@latest (currently 9) with typescript@next

Test failures with typescript@next are fixed by #3488 

[no-log]

### CODE REVIEW

**Comment by ajafff** [comment]
This change also allows you to configure which CI jobs are required before merging PRs.
That means we can make `testNext` optional to avoid blocking PRs because of unrelated CI failures. Ref: https://github.com/palantir/tslint/pull/3485#issuecomment-344525048

**Comment by adidahiya** [comment]
I will merge and you can fix any issues that show up on develop

> That means we can make testNext optional to avoid blocking PRs because of unrelated CI failures. 

this sounds like a good idea, feel free to make this change

**Comment by ajafff** [comment]
@adidahiya 

> > That means we can make testNext optional to avoid blocking PRs because of unrelated CI failures.
>
>this sounds like a good idea, feel free to make this change

That's something you have to configure in the repo settings: https://circleci.com/docs/2.0/workflows-waiting-status/
disable: ci/circleci
enable: ci/circleci: build, ci/circleci: lint, ci/circleci: test, ci/circleci: test2.1, ci/circleci: test2.4

**Comment by adidahiya** [comment]
@ajafff done

**Pull request merged**
