### PR TITLE
(feature): FixFormatter: new formatter for printing fixed files

### PR DESCRIPTION
**Pull request by ianks**
#### PR checklist
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests

#### What changes did you make?

This PR adds a FixFormatter which take a single file, and prints the fixed contents of said file. The goal is to be able to integrate with editor plugins such as [neoformat](https://github.com/sbdchd/neoformat), which rely on the  the formatted text being printed to stdout.

Currently, this formatter will only work when passing in a single file. I think from a practicality standpoint, this makes a lot of sense as the output will always be merged into a single stream (stdout, some file, etc), where the end user probably will not want to merge all of the files together.

Happy to any suggestions and improve this in any way you see fit!

-Ian

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @ianks! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by ianks** [comment]
@nchen63 why was this closed?

**Comment by nchen63** [comment]
The approach of using a formatter just isn't feasible given my reasons above.

**Comment by ianks** [comment]
Ok, so what would be the best way to get this feature implemented? Should we continue the discussion in https://github.com/palantir/tslint/issues/2125?

**Comment by nchen63** [comment]
sure, let me know if my idea of copying the file doesn't work

**Pull request closed without merging**
