### PR TITLE
Revert "Need to add @types/node to reg dependencies since we use `Error` interface"

### PR DESCRIPTION
**Pull request by adidahiya**
Reverts palantir/tslint#1739

### CODE REVIEW

**Comment by nchen63** [comment]
Yeah, it's not the right thing to do, but we should still address this error when compiling when tslint is installed as a library:

```
node_modules/tslint/lib/configuration.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
```

**Comment by adidahiya** [comment]
@nchen63 how exactly did you get that error -- did you set up a new test project? We could make a note in the docs

**Comment by nchen63** [comment]
Yeah, I set up a test project and installed from an `npm pack` package

**Comment by nchen63** [comment]
I feel like there should be a way to make it work that doesn't require users to install node typings. Pre-2.0 typescript did not generate the `/// <reference types="node" />` header which causes this issue. If we can avoid exporting functions that use the `Error` interface, that would work too

**Pull request merged**
