### PR TITLE
Add fixer for commentFormatRule

### PR DESCRIPTION
**Pull request by QuentinFchx**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [ ] Documentation update

#### What changes did you make?

Add a fixer for `commentFormat` rule

#### Is there anything you'd like reviewers to focus on?

I quickly tried to fix lower/upper case but I don't really know how replacement stack is applied (fifo/lifo?). I can add a fix in this PR if necessary

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @QuentinFchx! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by ajafff** [comment]
> I don't really know how replacement stack is applied

Replacements are sorted by their start position in descending order. Overlapping replacements are not really possible.
In your case if you want to add one space and change the first character to upper/lower, you would have the same start index. Unfortunately `Array.prototype.sort()` does not guarantee that the order is preserved.

I don't have a good idea how to fix both.

**Comment by nchen63** [comment]
To handle the case for a comment with multiple errors, you could emit one error instead of multiple errors and generate a string that describes multiple problems. The fix would then fix all of the problems at once.

**Comment by adidahiya** [comment]
Closing for now, feel free to push changes & leave a comment here if you'd like us to re-open the PR.

**Pull request closed without merging**
