### PR TITLE
Simplify code for adding failures

### PR DESCRIPTION
**Pull request by andy-hanson**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update
- [X] Code improvement

#### What changes did you make?

This greatly simplifies how to add new rule failures, using just a few helper functions.
Only 2 rules remain that directly call `createFailure`; these two keep their own list of failures and do complex things with them.  All other rules were just creating a failure and immediately adding it, so those steps can be combined.

### CODE REVIEW

**Comment by adidahiya** [comment]
@andy-hanson could you please enable Circle CI for your fork? I'd be happy to merge this after it is verified by CI.

**Comment by andy-hanson** [comment]
How do I do that?

**Comment by adidahiya** [comment]
@andy-hanson go to https://circleci.com/gh/andy-hanson/tslint and look for the button to enable builds for the project

**Comment by andy-hanson** [comment]
OK, enabled it.

**Comment by andy-hanson** [comment]
Created #1867 for that. It requires some non-trivial changes but I think it's doable.
Making it `private` will cause pretty much every custom rule to have compile errors, but in most cases it will be easy to translate to `addFailureAtNode`. Just noting that people could use some heads-up.

**Comment by adidahiya** [comment]
good point

**Pull request merged**
