### PR TITLE
Exclude globs

### PR DESCRIPTION
**Pull request by blakeembrey**
Closes https://github.com/palantir/tslint/issues/915. Very simple, but I've need it for a while :smile:

### CODE REVIEW

**Comment by JKillian** [comment]
Seems good to me! Could you add documentation in `tslint-cli.ts` for the new command and copy it to the README as well before we merge this? (Just amend this commit, no need for a second commit.)

**Comment by JKillian** [comment]
Thanks @blakeembrey! I'll update the documentation myself, no worries

**Comment by blakeembrey** [comment]
@JKillian Sorry! I've been meaning to get to this, but I didn't suspect it'd be until this weekend. Let me know when there's a patch, I'd love to start using this :smile:

**Comment by Healforgreen** [comment]
@blakeembrey +1

**Comment by adidahiya** [comment]
this is available in the 3.6 release btw, as indicated by the milestone

**Comment by blakeembrey** [comment]
Thanks @adidahiya! Using it https://github.com/typings/core/blob/master/package.json#L12 already :+1:

**Comment by Healforgreen** [comment]
@adidahiya Thanks!  Sorry, I'm blind :(

**Pull request merged**
