### PR TITLE
Add "format" rule category

### PR DESCRIPTION
**Pull request by andy-hanson**
#### PR checklist

- [X] Addresses an existing issue: #2759 (half of it)
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [X] Documentation update

#### Overview of change:

Adds a new RuleType and switches many rules to it.
The "format" category is for rules which would be handled by a formatter; these are rules which control the way an AST is represented as text.
I'm on the fence about whether to include "curly" here. It seems like a format-only rule, but I think a formatter would preserve whether you used curly braces around a one-line statement.

### CODE REVIEW

**Comment by giladgray** [comment]
@andy-hanson please update this branch so we can review it, or close it if not relevant.

**Comment by andy-hanson** [comment]
Running `git commit` normally broke a bunch of stuff, had to redo with `git commit --no-verify`.

**Comment by JoshuaKGoldberg** [comment]
> Running `git commit` normally broke a bunch of stuff, had to redo with `git commit --no-verify`.

Should no longer be an issue for later updates after merging in from `master` now that #4214 and #4270 are in.

**Comment by adidahiya** [comment]
I will merge this but I would like to change the category name to "formatting", i'll do that in a separate PR

**Pull request merged**
