### PR TITLE
Really fix type parameter of applyWithFunction

### PR DESCRIPTION
**Pull request by ajafff**
#### PR checklist

- [x] Addresses an existing issue: #2396
- [x] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Overview of change:
Followup on #2396:
Using `U extends T` allows excess properties.
Using `{} & T` does stricter type checking (no more excess properties and enables linting the parameter with `no-unsafe-any`) and also fixes the inference problem with arrow functions: https://github.com/palantir/tslint/pull/2396#issuecomment-290993472

#### Is there anything you'd like reviewers to focus on?
This change may technically break dependent libraries if they explicitly specified the type parameters. In reality possibly noone ever did that. On the other hand this change may reveal bugs during type checking.
#### CHANGELOG.md entry:

[api] `AbstractRule#applyWithFunction` has better type checking for its type parameter

### CODE REVIEW

**Comment by nchen63** [comment]
`{} & T` doesn't seem to be encouraged https://github.com/Microsoft/TypeScript/issues/14829#issuecomment-298427189

**Comment by ajafff** [comment]
Seems like this is now the preferred way to exclude a parameter from type inference. It's even suggested by TypeScript devs https://github.com/Microsoft/TypeScript/issues/17491#issuecomment-318720788

**Comment by ajafff** [comment]
CI failed to compile. Looks like this solution will not work for all cases. 
I'll investigate further and try to find a working solution.

**Comment by ajafff** [comment]
I managed to work around the type error. Cross posting https://github.com/Microsoft/TypeScript/issues/14829#issuecomment-322267089 for reference

> `T & {}` only works when not using `strictNullChecks`.
>I encountered a problem when `T` is `undefined`, because `undefined` is not assignable to `undefined & {}`.
>
>I found that mapped types also defer inference, so i tried `type InferLast<T> = Readonly<T>;`
>That does not work for types with index signatures like arrays.
>
>My final solution is a mapped type intersected with the type itself:
>
>```ts
>export type NoInfer<T> = T & {[K in keyof T]: T[K]};
>```

**Pull request merged**
