### PR TITLE
Improve the UI for the rules documentation

### PR DESCRIPTION
**Pull request by chrismbarr**
### PR checklist

- [ ] Addresses an existing issue: #0000
- [x] enhancement
  - [ ] Includes tests
- [x] Documentation update

### Overview of change:
This PR make some UI changes to the the list of rules, and the individual rule detail pages.

- The rules on the rules list page are now clickable, not just the rule name
- Alternating background colors + hover colors
- "feature" badges for each rule in the list, and larger versions on the actual rule details page
  - yellow badge with document icon when `typescriptOnly` is true
  - green badge with wrench icon when `hasFix` is true
  - red badge with info icon when `requiresTypeInfo` is true

**Here's what the changes look like!**
tslint-docs

Eventually it would be really nice to have some interactive rule filters on that page.  To be able to filter the rules list down to only show the rules that require type info, or could be auto-fixed would be awesome!  I wanted to keep this PR minimal & focused though.

### CODE REVIEW

**Comment by chrismbarr** [comment]
This shows that CircleCI is still running the tests, but clicking through to the details shows that they all passed!  perhaps this was related to the Amazon S3 outage yesterday?

**Comment by nchen63** [comment]
For some reason, the info icon doesn't render for me (Chrome/OSX)

screen shot 2017-03-01 at 12 25 40 pm

**Comment by chrismbarr** [comment]
@nchen63 Hmm, that's odd, it's just a standard unicode symbol.  Here's a test page for that symbol, does it render here?

http://www.fileformat.info/info/unicode/char/1f6c8/browsertest.htm

What about this one?  This could be switched out: http://www.fileformat.info/info/unicode/char/2139/browsertest.htm

**Comment by adidahiya** [comment]
@chrismbarr your first link doesn't work for me, but the [second one](http://www.fileformat.info/info/unicode/char/2139/browsertest.htm) does

**Comment by chrismbarr** [comment]
Ok, change made.  Here's what it now should look like

image

**Comment by nchen63** [comment]
The circle is weirdly stretched out on my browser

screen shot 2017-03-02 at 3 52 26 pm

I pushed a commit to your branch that should fix the issue. Can you see if it looks ok on your side?

**Comment by chrismbarr** [comment]
Ah good idea, that's a better solution to fix the width to the width to `1em;`  I had to move that up to apply to the redular sized badges as well, you added them to just the smaller ones that appeared in the rules list.

The larger ones appear on the actual rules page, and they looked like this:
2017-03-03 07_40_22-rule_ promise-function-async

But I've fixed that now!

I tested this on Windows 10 in Chrome, Firefox, Edge, IE11, IE10, and IE9 - all look good.  Edge & all IE's render the icons a but different using the solid color non-emoji look to them, but they work.

**Comment by nchen63** [comment]
@chrismbarr thanks!

**Pull request merged**
