### PR TITLE
Added only-throw-errors rule

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
#### PR checklist

- [x] Addresses an existing issue: #1465
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [ ] Documentation update
- [x] Enable CircleCI for your fork (https://circleci.com/add-projects) *(I think)*

#### What changes did you make?

If something is being thrown whose type is known, its type and base
types must contain the `"Error"` class.

#### Is there anything you'd like reviewers to focus on?

Not feeling great about what I named the `utils` functions.

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Having problems with the `e` in `catch (e)`, otherwise works...

**Comment by adidahiya** [comment]
we already have [`no-string-throw`](https://github.com/palantir/tslint/pull/1878)... this needs to be reconciled with that rule. is there a significant advantage to using the type checker here?

**Comment by JoshuaKGoldberg** [comment]
Oh, missed that rule! The comments from you, @andy-hanson and @nchen63 are relevant.

This is a situation where the rules do basically the same thing, but one is more powerful because it can use the type checker. There are four options I can think of:
1. Only have the weaker, easier-to-use rule *(current)*
2. Have both rules
3. Only have the stronger, harder-to-use rule
4. Allow for rule logic that only gets activated

Option 4 is interesting, and could be really useful in situations like this. It'd give the best of both worlds without requiring extra user configuration. Think I should file a separate issue?

**Comment by andy-hanson** [comment]
`"unknown"` is the type you get when there's a compile error that prevents you from getting the type.
If I copy-paste that code into VSCode I get correct information on hover, so maybe there's a compile error somewhere else that effects that? Try copying your test code into a '.ts' file and seeing what errors show up.

**Comment by nchen63** [comment]
I think option 4 would be ideal but the details might get messy since this would be the first dual rule. Also, the name `no-string-throw` isn't quite right and changing it would be a breaking change.

**Comment by JoshuaKGoldberg** [comment]
Moved issue to new thread.

**Pull request closed without merging**
