### PR TITLE
Rewrite prefer-const

### PR DESCRIPTION
**Pull request by ajafff**
#### PR checklist

- [x] Fixes: #2068, #2195
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [x] Documentation update

#### What changes did you make?

[enhancement] show warnings for `var`
[bugfix] correctly handle variables shadowed by parameters and catched exceptions
[bugfix] don't warn if one variable in a for loop initializer can not be const
[bugfix] handle more cases in destructuring
[bugfix] only fix initialized variables
[new-rule-option] `{destructuring: "all"}` to only warn if all variables in a destructuring can be const

#### Is there anything you'd like reviewers to focus on?

Tests fail with typescript@2.0 because one test contains syntax (spread) which is not supported in that version of the language. In real life this will not result in a problem.
How to handle the ci failure?

### CODE REVIEW

**Comment by nchen63** [comment]
I don't think we should special case variable declaration in `for` loops. This makes sense:

```
for (const x of y) { ... }
```

The issue with #2195 actually didn't really have to do with `for` loops so much as declaring 2 things with the same `let`.

**Comment by ajafff** [comment]
@nchen63 I also thought about adding an option for multiple variables declared in the same `let`. But that can simply be fixed by using separate VaraibleStatements.

The special handling is only for `for`-loops, not `for ... of` or `for ... in`;
The reason is that for loops are the only place where you cannot split a VariableDeclarationList into multiple VariableStatements without moving a variable to another scope.

```ts
for (let foo of bar); // still fails
for (let foo in bar); // still fails
for (let foo=bar; someCondition;); // still fails because foo is not reassigned
let i = 0;
for (let len=foo.length; i<len;++i); // still fails because len is not reassigned

// this is the only case that does not fail anymore
// Otherwise you would need to move variable len out of the loop initializer to the parent scope, which could leed to unexpected behaviour if it shadows another variable
for (let i=0, len=foo.length; i<len; ++i); // no fail for len because i is reassigned
```

Btw: eslint also works that way.

**Comment by ajafff** [comment]
I made some further changes to correctly handle reassigned variables in parameter initializer.
Additionally fixes will now only be applied if all variables of a VariableDeclarationList are initialized to avoid compiler errors.

**Comment by ajafff** [comment]
Regarding the failing tests with older versions of typescirpt:

#2253 will eventually have the same problem and so will all future rules based on new language features or syntax.
I think we need a way to tell the testRunner to ignore certain tests for certain versions of typescript.

**Comment by ajafff** [comment]
The failing tests are now fixed. Should be ready to merge.

**Comment by nchen63** [comment]
@ajafff thanks!

**Pull request merged**
