### PR TITLE
Improve object shorthand

### PR DESCRIPTION
**Pull request by pablobirukov**
#### PR checklist

- [x] Addresses an existing issue: #3778
- [x] Enhancement
  - [x] Includes tests

#### Overview of change:

Support granular configuration in `object-literal-shorthand`

#### CHANGELOG.md entry:

[new-rule-option] `object-literal-shorthand` supports `{"property"?: "never", "method"?: "never"}` as config options

### CODE REVIEW

**Comment by michaeljota** [comment]
Please see #4141 before you contribute to this project. Thank you!

**Comment by JoshuaKGoldberg** [comment]
...and of course, merge conflicts. 😢. If you don't have time to resolve these soon @pablobirukov I can tackle them.

**Comment by pablobirukov** [comment]
Screw you, Prettier!

I'll fix those @JoshuaKGoldberg

**Comment by pablobirukov** [comment]
Pushed  #4842 instead @JoshuaKGoldberg

**Comment by adidahiya** [comment]
Closing in favor of #4842

**Pull request closed without merging**
