### PR TITLE
improved no-default-export rule

### PR DESCRIPTION
**Pull request by patsissons**
more tests for less common export statements. new code to handle inline class and function declarations (and possibly other inline declarations if any exist).

### CODE REVIEW

**Comment by patsissons** [comment]
fixes #1241

**Comment by JKillian** [comment]
Looks good to me! I know your code should handle this correctly, but mind adding a code that tests a switch statement with a default case? Figure we might as well ensure that that doesn't trigger a failure ever in the future by accident.

**Comment by patsissons** [comment]
sure no prob.

**Comment by JKillian** [comment]
👍  Merged!

**Pull request merged**
