### PR TITLE
no-empty: fix lack of methods handling

### PR DESCRIPTION
**Pull request by keradus**
#### PR checklist

- [x] Addresses an existing issue: #3624 => that is the feature PR that incorporate the bug
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [ ] Documentation update

#### Overview of change:
I do like #3624 and I wanted to use it.
It already has support for classes, as it has special test case with constructor, which is handled differently.
Yet, class might need to have an empty method - and even if one is using `allow-empty-function`, then empty method is considered as violation.
When empty method may be valid? Class implements interface, want to provide empty implementation for abstract method from parent class or one is using ducktyping.

#### CHANGELOG.md entry:

`[bugfix] allow-empty-functions option of no-empty rule is now properly respecting empty methods`

### CODE REVIEW

**Comment by keradus** [comment]
Thank you :heart:  Really nice to hear! (especially when I do equivalent soft for PHP)

Also, big :+1: for quick reaction, it's appreciated :+1:
Now, awaiting for bugfix release ;)

**Comment by keradus** [comment]
hi there @giladgray ! any chances for have this PR released ?

**Comment by keradus** [comment]
ping @giladgray, any chances?

**Comment by dh-tdoumtsis** [comment]
any news on that?

**Pull request merged**
