### PR TITLE
Fixed casing of names, added "more" link

### PR DESCRIPTION
**Pull request by 304NotModified**
#### PR checklist

- [x] Documentation update

#### Overview of change:
Changed readme:

- Added more link
- Fixed casing of names.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Sure, is it OK to link the "more" then to https://palantir.github.io/tslint/usage/third-party-tools/? (as we now have 2 lists?)

**Comment by 304NotModified** [comment]
and is the fix casing of names OK?

**Comment by 304NotModified** [comment]
update to myself: this file: https://github.com/palantir/tslint/edit/gh-pages/usage/third-party-tools/index.md

**Comment by ajafff** [comment]
The change in casing seems good to me.

> is it OK to link the "more" then to https://palantir.github.io/tslint/usage/third-party-tools/?

Makes sense IMO

The file you need to change to update the website is https://github.com/palantir/tslint/blob/master/docs/usage/third-party-tools/index.md on master

**Comment by adidahiya** [comment]
- casing fix is good
- link to "more" is good
- yes you need to edit the docs source on master
  - then, separately make a gh-pages PR with the compiled docs (`npm run docs`, copy the changes to a new branch off `gh-pages`)... maintainers will eventually do this for you when releases are made

**Comment by 304NotModified** [comment]
Updated it, I assume squash is not needed as Github can Squash now :)

**Pull request merged**
