### PR TITLE
Add `callable-types` rule

### PR DESCRIPTION
**Pull request by andy-ms**
#### PR checklist

- [X] Addresses an existing issue: #1844
- [X] New feature, bugfix, or enhancement
  - [X] Includes tests
- [X] Documentation update

#### What changes did you make?

Added the `callable-types` rule, which recommends to use a function type over an interface or type literal with just a call signature.

### CODE REVIEW

**Comment by nchen63** [comment]
@andy-ms thanks!

**Comment by CodeOtter** [comment]
I've found having a module with common interfaces for callbacks improves code readability.  For example:

```
export interface IError {
  (
    message: string,
    data: any,
  ): void;
}

export interface IDone {
  (
    error: any,
    data: any,
  ): void;
}

export interface INext {
  (
    error: any,
    data: any,
  ): void;
}

export interface IPassthru {
  (
    data: any,
  ): void;
}
```

This rule appears to prevent this.  I'll be turning this rule off in my local tslint.json, but I'm curious what problem this rule is solving.  Thanks!

**Comment by andy-ms** [comment]
You can just as easily use a type alias.
```ts
export type Error = (message: string, data: any) => void;
```
Also, in your example, if you used a specific function type instead of using a common one, you could avoid using `any`. You could also use a generic: `export type Error<T> = (message: string, data: T) => void`.

**Comment by CodeOtter** [comment]
Oh my.  Most helpful, @andy-ms   Thanks for the breakdown!

**Pull request merged**
