### PR TITLE
Added Gitpod to third-party tools

### PR DESCRIPTION
**Pull request by svenefftinge**
Gitpod comes with TSLint support.
screenshot 2018-11-19 at 11 34 32

You can try it on this PR:
[Open in Gitpod](https://gitpod.io/#https://github.com/palantir/tslint/pull/4299)

Also thank you for this great project. We use it in every TS project. :heart:

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @svenefftinge! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by JoshuaKGoldberg** [comment]
👋 @svenefftinge, thanks for this! I hadn't heard of Gitpod till now.

Applying it to this PR: https://d0e51df3-9704-4186-b16a-828ad2e33078.ws-us.gitpod.io, there are some file casing problems from `yarn run test:rules` within `yarn run verify`:

image

Looks like a bug in Gitpod? Before considering adding it to this list, it should work.

**Comment by svenefftinge** [comment]
Good catch! We need to support git clone flags `--config core.autocrlf=input --config core.eol=lf`.
We will fix it and ping you here when it's fixed/supported. Thank you! 👍 
Ticket: https://github.com/gitpod-io/gitpod/issues/152

**Comment by svenefftinge** [comment]
It is fixed now. The `.gitpod.yml` configuration for your project is here:
https://github.com/gitpod-io/definitely-gp/blob/master/tslint/.gitpod.yml

You can of course alternatively check it into your repo :-)

**Pull request merged**
