### PR TITLE
Add a formatter to apply fixes

### PR DESCRIPTION
**Pull request by alexeagle**
partially addresses #1534

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @alexeagle! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by alexeagle** [comment]
Looks like CI is broken by the TS upgrade, independent of my change? master is green but maybe a caching issue...

**Comment by adidahiya** [comment]
Yep, I believe master is broken. Looking into it now.

**Comment by adidahiya** [comment]
Tried to fix master in the simplest way possible but this adds a TS 2.0 minimum dependency: https://github.com/palantir/tslint/pull/1575. Not sure if we want TSLint 4.0 to require TS 2.0; will think about this when I have time in the next few days.

**Comment by alexeagle** [comment]
Green now, PTAL?
If you or @JKillian have some cycles this week, I'd like to wrap up my present effort on tslint and get back to 80% work :)

**Comment by JKillian** [comment]
Don't have a chance to look over this right now, but feel free to merge if it looks good to you @adidahiya! Added this to the 4.0 milestone because we should definitely merge this before then

**Pull request merged**
