### PR TITLE
Ban chained methods

### LINKED ISSUE #1234: Chained methods aren't banned properly
### Bug Report

- __TSLint version__: `3.9`
- __TypeScript version__: `1.8.10`
- __Running TSLint via__: `gulp-tslint`

#### TypeScript code being linted

```ts
_.keys(obj).forEach((key: string) => console.log(key));
```

with `tslint.json`:

```json
{
  "rules": {
    "ban": [true,
        [ "_", "forEach" ],
        [ "_", "each" ],
        [ "$", "each" ],
        [ "angular", "forEach" ]
    ]
}
```

#### Actual behavior

`function invocation disallowed: _.forEach`

#### Expected behavior

It should pass since `forEach` is native Array method (`_.keys()` doesn't even return `_`).

Splitting it to:

```javascript
var keys: string[] = _.keys(obj);
keys.forEach((key: string) => console.log(key));
```

passes linting.

### PR DESCRIPTION
**Pull request by marines**
Fixes #1234

### CODE REVIEW

**Comment by marines** [comment]
Any ideas why is this failing?

**Comment by JKillian** [comment]
Code looks good to me! Can we add one more test case to make sure that the issue you were experiencing in #1234 doesn't produce a lint failure?

**Comment by marines** [comment]
Of course. :)

**Comment by JKillian** [comment]
Thanks, merged!

**Pull request merged**
