### PR TITLE
Upgrade prettier and run over all files

### PR DESCRIPTION
**Pull request by aboyton**
#4012 added prettier support but then didn't run it over everything and turned it on for YAML files despite using a version that doesn't support YAML.

This:
* Upgrades Prettier to  1.14 whic adds yml support.
* Turns on `trailing commas = all` as that seems to be what most of the code is doing.
* Runs prettier over everything

This also has the bonus of making future PRs much smaller.

#### PR checklist

- [ ] Addresses an existing issue: #0000
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Overview of change:
As above, this upgrades Prettier, sets an option and runs it over everything.

#### Is there anything you'd like reviewers to focus on?

Not much as this is autogenerated but we should check that it hasn't broken anything.

#### CHANGELOG.md entry:

* Upgrade Prettier, turn on `trailingComma: "all"` and run it over all files.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @aboyton! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by johnwiseheart** [comment]
I think its probably a good idea to merge this. @giladgray thoughts?

**Comment by JoshuaKGoldberg** [comment]
@johnwiseheart this is creating a lot of noise for other PRs. I'll go ahead and merge this in.

**Comment by aboyton** [comment]
I'm very happy to rebase this if that would help.

**Comment by JoshuaKGoldberg** [comment]
@aboyton it's ready to be merged except it fails on `typescript@next` for `object-literal-key-quotes ☹... I can repro locally and am trying to figure it out now. If you can fix it, that'd be great too!

**Pull request merged**
