### PR TITLE
trailing-comma: add option to forbid trailing comma after rest

### PR DESCRIPTION
**Pull request by ajafff**
#### PR checklist

- [x] Addresses an existing issue: #3147
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [x] Documentation update

#### Overview of change:
Add an option `"specCompliant"` to the rule. Enabling that option forbids trailing commas after object and array rest as well as rest parameters. That makes the linted code compatible with the ES spec and the implementation in JS VMs.
Fixes: #3147

#### Is there anything you'd like reviewers to focus on?

Do you know a better option name than `specCompliant`?

#### CHANGELOG.md entry:

[new-rule-option] `trailing-comma` adds option `"specCompliant"` to make it compatible with the ES spec regarding trailing commas after object/array rest and rest parameters.

### CODE REVIEW

**Comment by IllusionMH** [comment]
Shouldn't be the problem, but tests can be added for combination of arguments destructuring and regular params later and vice versa
```ts
function combined([a, ...arr], {b, ...obj}, regular) {}
                                                   ~ [Missing trailing comma]

function combined([a, ...arr,], {b, ...obj,}, regular,) {}
                            ~ [Forbidden trailing comma]
                                          ~ [Forbidden trailing comma]
```

**Comment by ajafff** [comment]
@IllusionMH I just added tests as suggested

> Is it worth to consider adding `specCompliant: true` to `tslint:recommended` config at least for next major update?

We should definitely enable it for .js files. And to keep it consistent we should also enable it for .ts files.
Users who want to use trailing commas everywhere in their typescript files, can disable it using `specCompliant: false`.

I'm thinking about renaming the option to something like `"mode": "spec"` and `"mode": "consistent"`. Thoughts?

**Comment by adidahiya** [comment]
What does `"mode": "consistent"` convey? "spec compliant" sounds a little more intuitive to me, but I would suggest making it even more verbose as `esSpecCompliant`

**Comment by ajafff** [comment]
> What does `"mode": "consistent"` convey?

It would enable you to consistently use traling commas everywhere in your TypeScript code. Not a great idea on second thought, since it's inconsistent with how JavaScript works.

Renamed to `"esSpecCompliant"` as suggested.

**Comment by adidahiya** [comment]
master is broken (semantic merge conflict?) but this PR looks gtg

**Comment by ajafff** [comment]
That's not a merge conflict. The typescript@next changed the error message (and detection algorithm) for unused variables.
I'm working on a fix right now.

**Comment by thgreasi** [comment]
Woohoo!

**Pull request merged**
