### PR TITLE
[enhancement] Update devDependency nyc from v13.3.0 to v14.1.1

### PR DESCRIPTION
**Pull request by bjornstar**
#### PR checklist

- [x] New feature, bugfix, or enhancement

#### Overview of change:

There is a vulnerability in handlebars for v13 of nyc, update to the latest version to avoid it.

#### Is there anything you'd like reviewers to focus on?

New coverage summary:

```
Statements   : 46.31% ( 5007/10812 )
Branches     : 39.94% ( 2664/6670 )
Functions    : 45.46% ( 881/1938 )
Lines        : 46.22% ( 4445/9617 )
```

Current coverage summary:

```
Statements   : 37.08% ( 4245/11449 )
Branches     : 24.12% ( 1646/6823 )
Functions    : 33.96% ( 868/2556 )
Lines        : 36.78% ( 3756/10212 )
```

#### CHANGELOG.md entry:

[enhancement] Update devDependency nyc from v13.3.0 to v14.1.1

### CODE REVIEW

**Comment by bjornstar** [comment]
Raised an issue over at nyc -- https://github.com/istanbuljs/nyc/issues/1111

**Comment by bjornstar** [comment]
The istanbul team was very helpful and now we have improved coverage, this is ready to go.

**Comment by adidahiya** [comment]
Try merging master now that #4731 is in to fix the testNext build

**Comment by bjornstar** [comment]
> Try merging master now that #4731 is in to fix the testNext build

The test is passing now.

**Review by adidahiya — APPROVED** [review]
great, thanks @bjornstar

**Pull request merged**
