### PR TITLE
Remove some difficult recommended rules

### PR DESCRIPTION
**Pull request by aghoneim92**
#### PR checklist

- [ x ] Addresses an existing issue: #4305 
- [ x ] New feature, bugfix, or enhancement
- [ x ] Includes tests
- [ x ] Documentation update

#### Overview of change:

Removed the following four rules from the recommended toolset:
1. interface-name
2. member-access
3. object-literal-sort-keys
4. ordered-imports

#### Is there anything you'd like reviewers to focus on?

Should we remove even more rules? I personally don't like `member-ordering` either.

#### CHANGELOG.md entry:

[enhancement] remove pedantic rules from the `recommended` config

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @aghoneim92! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by JoshuaKGoldberg** [comment]
LGTM! I'll resolve these merge conflicts so we can get this in. 💪

**Comment by JoshuaKGoldberg** [comment]
This is ready to go in! @aghoneim92, would you mind resolving merge conflicts? If not I can send a separate PR.

**Comment by JoshuaKGoldberg** [comment]
#4871 is a superset of this.

**Comment by adidahiya** [comment]
personally, I like `member-access` and `ordered-imports`. especially the latter since it has a nice auto-fixer. I would like to bring these back in a new `tslint:strict` ruleset

**Pull request merged**
