### PR TITLE
Converted runner.ts to use Promises

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Moves all of `run`'s logic to a `runAsPromise` that uses async/await.

This uses the `mz` package. I'm curious on your opinions on this: should TSLint do work to wrap the `fs` APIs in Promises, or take on the package as a dependency?

Starts on #2328.

### CODE REVIEW

**Comment by andy-hanson** [comment]
* A class with a single method invoked immediately after construction is a code smell. I don't think `Runner` is meant to be public (#2446). You could just use a function `run` returning a Promise.
* `status` could be a const enum.

**Comment by ajafff** [comment]
> I don't think Runner is meant to be public

IIRC @JoshuaKGoldberg was the one who exported it, hence I guess it is used in the wild.

I don't really see a benefit in just using Promises but then awaiting them all of the time. As it is now there will only be overhead with nothing gained.
IMO it would make more sense to run async fs functions in parallel no matter if callback style or promisified.

**Comment by JoshuaKGoldberg** [comment]
> code smell

Interesting. How would you prefer the runner logic be written? 

> public
> 2446

The idea behind separating out `Runner` from the cli logic was that external users might want to be able to use it instead of spinning up a whole Node sub-process. I specifically wanted to experiment with https://github.com/automutate/autotslint. I don't think anybody else uses it, so if it's not (yet/ever) part of the public contract I'm fine with changing `run`.

> `status` could be a const enum.

Agreed! #2182 - since nobody's responded, I think I can send a quick separate PR for this soon.

> overhead 

Even as a prerequisite for #2328?

**Comment by andy-hanson** [comment]
> How would you prefer the runner logic be written?

I wasn't commenting on the way it was implemented but on the way it is exposed. You wouldn't do e.g. `new Adder(1, 2).add()`, so why have `new Runner().run()`?
In terms of implementation, just unindent everything, move the constructor parameters to `run`, and replace `public` with `export function` and `private` with `function` (adding explicit parameters for the members of `this` that were used there).

**Comment by JoshuaKGoldberg** [comment]
I'm not sure I agree with the idea of using plain functions over a class for the runner logic. Right now it has two objects that are used, `options` and `outputStream`, which would have to be passed to (nearly) every function. That itself feels like code smell. What do we do when there are other hooks added, such as performance tracking or a file I/O interface? I see three roads there:
1. Pass a whole bunch of objects around to each function
2. Create a "dependencies" object and pass it to each function
3. Use a class

Is option 1 maintainable? Option 2 is made simpler by using 3 instead.

**Comment by andy-hanson** [comment]
If you find that everything in your program needs to have access to everything else, the solution isn't to put it all in one class! It can be broken down into simple components. See #2572.

**Comment by JoshuaKGoldberg** [comment]
Sure. I'd love to discuss this further but your PR looks better :)

**Comment by andy-hanson** [comment]
Thanks!
But, mine doesn't use Promises, so you might want to leave this open...

**Comment by JoshuaKGoldberg** [comment]
I'll send a new PR when yours is in.

**Pull request closed without merging**
