### PR TITLE
Support `no-consecutive-blank-lines` and `no-default-export` for Vue single file components

### PR DESCRIPTION
**Pull request by akoidan**
#### PR checklist

- [ ] Addresses an existing issue: fixes #0000
- [x] New feature, bugfix, or enhancement
- [x] Includes tests
- [x] Documentation update

#### Overview of change:

This PR is focused on integrating with Vue single file component. There're two features added:
 - Ignore default export from `.vue` files, since [Vue will never support non-default export](https://github.com/vuejs/vue-loader/issues/1234#issuecomment-409020334)
 - Ignore <template> option in `.vue` file so `no-consecutive-blank-lines` works. The template issue is below:

```
<template>
<div>asd</div>
</template>
<script lang="ts">
export default {
}
</script>
```
vue-loader will transpile into:
```




export default {
}

```
     

#### CHANGELOG.md entry:
-  [new-rule-option] `"no-consecutive-blank-lines": [true, {"trim-left-pattern": "\\.vue$"}]`
-  [new-rule-option] `"no-default-export": [true, {"ignore-pattern": "\\.vue$"}]`

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @akoidan! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by akoidan** [comment]
`test/rules/no-inferred-empty-object-type/test.ts.lint: Failed!` Fails in master on typescript@next

**Comment by JoshuaKGoldberg** [comment]
Confirmed, we can ignore the testNext failures: #4644

**Comment by akoidan** [comment]
@JoshuaKGoldberg thanks for the review. Could you please take a look at `Overview of change` section. I describe everything there. If something needs to be clarified, you can shoot any question. 

The main idea is to improve [Vue](https://github.com/vuejs/vue) single file component linting support. As for now I see 2 issues:
 - There's no way to enable `no-default-export` option in `.ts` files but having them disabled in `.vue` files. [It's impossible to get rid of default export in `.vue`](https://github.com/vuejs/vue-loader/issues/1234#issuecomment-409020334).
 - `no-consecutive-blank-lines` doesn't work in `.vue` files since to enable sourcemaps `vue-loader` will leave blank spaces in `<template>` section and this will never change.

**Comment by adidahiya** [comment]
Sorry, as per the roadmap #4534, I'd like to avoid adding nonessential rule options at this point. I believe ESLint can be configured to exclude certain file types for rules with `excludedFiles` overrides: https://eslint.org/docs/user-guide/configuring#example-configuration

**Pull request closed without merging**
