### PR TITLE
Add package.json scripts for easier development

### PR DESCRIPTION
**Pull request by andy-hanson**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update
- [X] Infrastructure

#### What changes did you make?

Added scripts allowing one to run the compiler in `--watch` mode and run specific tests.

#### Is there anything you'd like reviewers to focus on?

* Another idea: could `ruleTestRunner` generate mocha tests? Then we could use mocha's builtin functionality for filtering tests.
* Why does the `test` directory feature its own compilation of `src`, anyway? I was confused when recompiling `src` didn't affect tests.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Is there a way to compile/run the unit tests for only a single rule? If not that'd be a very useful addition imo.

**Comment by IllusionMH** [comment]
@SimonSchick I was achieving this by rewrite of `test/ruleTestRunner.ts` file for running single test folder (calculated based on `*Rule.ts` file name) from VSCode debugger.

If maintainers/collaborators think that it might be good approach (it will be implemented as separate file for debug purposes only), I'll submit PR for single rule folder debug this or (most probably) next weekend.

**Comment by adidahiya** [comment]
@SimonSchick yeah, that's currently possible using the CLI:

```sh
// global tslint
// point to a dir that has tslint.json and .lint files
tslint --test test/rules/semicolon/always

// locally built tslint
./bin/tslint --test test/rules/semicolon/always
```

**Comment by andy-hanson** [comment]
@adidahiya Maybe I should remove the changes to `ruleTestRunner.ts` and just have `contributing/index.md` tell people to use the commands you provided.

**Comment by nchen63** [comment]
closing in favor of #2025

**Pull request closed without merging**
