### PR TITLE
type-literal-delimiter: Add an option to enforce delimiter even in one liners; add fixes

### PR DESCRIPTION
**Pull request by r00ger**
_Addresses #3959_

#### Overview of change:

Some of us prefer having semicolons after type literal members even in a one-line statement, 

```ts
// e.g.
{ bar: number; }
// over 
{ bar: number }
```
that's why I've added a new config option to support this behavior.

Also, I've added a fixer that adds missing semicolons and replaces commas with semicolons

#### CHANGELOG.md entry:
[new-rule-option] `{ singleLine:  "always" | "never"}` for rule [type-literal-delimiter](https://palantir.github.io/tslint/rules/type-literal-delimiter/)

[new-fixer] [type-literal-delimiter](https://palantir.github.io/tslint/rules/type-literal-delimiter/)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @r00ger! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by r00ger** [comment]
Any chance to have this trivial change reviewed?

**Comment by ulrichb** [comment]
@r00ger Thank you very much for this!

**Comment by glen-84** [comment]
The option should probably have been named `singleline` (all lower case), for consistency with the `trailing-comma` rule.

(TBH, they should both actually be `single-line`, because it's not one word, and most options use kebab-case)

**Comment by jasonswearingen** [comment]
@pablobirukov your contribution is great, I found it and am using it.  However the docs are not clear.   could you or one of the maintainers please add an example of how to configure it properly.

After many tries, I found that this works:

```json
"type-literal-delimiter": {
            "options": {
                "singleLine": "always"
            }
        },
```

**Comment by JoshuaKGoldberg** [comment]
> could you or one of the maintainers 

@jasonswearingen TSLint is generally open to contributions that expand docs. You're welcome to file an issue & send a PR if you'd like! 😄

**Comment by jasonswearingen** [comment]
I've just started using tslint aggressively, so I have a high degree of uncertainty if my options choice is "correct"

I'll take your advice once I get more used to it thought!

**Pull request merged**
