### PR TITLE
[bugfix] Completed docs rule can check single-line comments

### PR DESCRIPTION
**Pull request by PomanoB**
#### PR checklist

- [x] Addresses an existing issue: #3365
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests

#### Overview of change:
Completed docs rule can check single-line JSDoc comments

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Thanks for the PR @PomanoB but there's already a PR out to fix this issue: https://github.com/palantir/tslint/pull/3557

**Comment by PomanoB** [comment]
Yes, but #3557 is more complex and unknown when it is merged(
Of course, you can close this pull-request if not agree with small fix or #3557 is coming

**Comment by PomanoB** [comment]
@giladgray done.

**Comment by giladgray** [comment]
easy enough

**Pull request merged**
