### PR TITLE
no-unused-variable: Create a duplicate SourceFile

### PR DESCRIPTION
**Pull request by andy-hanson**
#### PR checklist

- [X] Addresses an existing issue:  #2736, #2728, #2649
- [X] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Overview of change:

I tested out on https://github.com/CSchulz/tslint-no-unsafe-any-showcase and this fixed that issue. Hopefully this can fix the errors in VSCode too, but I'd need confirmation. CC @egamma

#### CHANGELOG.md entry:

[bugfix] `no-unused-variable`: Create a duplicate SourceFile

### CODE REVIEW

**Comment by egamma** [comment]
@andy-hanson having this problem fixed would be great. 

To verify the fix you need to run on case insensitive system like Windows.

Is there a build of tslint in npm that I could try to verify the fix?

If desired I can come up with steps for how to verify the fix with the tslint-language-service plugin.

**Comment by nchen63** [comment]
https://github.com/Microsoft/TypeScript/issues/15344

**Comment by andy-hanson** [comment]
@egamma You could try with a linked copy? Clone my branch, `yarn`, `yarn compile`, and the binary is in `./bin/tslint`, with `.js` files in `./lib`.

**Comment by CSchulz** [comment]
Works for me on Windows.

**Comment by egamma** [comment]
@andy-hanson with the fix I can no longer reproduce the problem in the TS server plugin, which is great.

However, I have a question about the implementation of this rule in general. One goal of running tslint as a TypeScript server plugin is to reuse/share the Program that the TS server already maintains. Doesn't the current implementation of the no-unused-variable rule create another Program with copies of Source files for each run of the rule? While this is OK when the program is run from the command line, when the rule is run in the TypeScript server as part of the tslint-plugin, then the rule is run as the user types. Will this implementation scale with large Programs?

Also I'm still concerned about the implementation of [getCaseSensitiveFileNames](https://github.com/andy-hanson/tslint/blob/713649ab669942fb0fd8f9ba07893e40155541da/src/rules/noUnusedVariableRule.ts#L384) which is hardcoded to:

```
useCaseSensitiveFileNames: () => true,
```
Won't this bite at some point?

**Comment by andy-hanson** [comment]
@egamma 
Yeah, that could end up doing a bit of work as just calls `getPreEmitDiagnostics` and filters out the diagnostics that aren't from an unused variable, meaning it will need to get type information from other files.
I added a commit that limits the Program to a single source file, meaning all imports will fail to resolve. That should prevent it from doing a lot of extra work. The program will still end up being checked twice though.

**Comment by egamma** [comment]
@andy-hanson this is a good move. 

>I added a commit that limits the Program to a single source file, meaning all imports will fail to resolve.

Does the rule still need access to the original Program? In other words does the rule still need to be a TypeRule?

Stepping back, the trick with using the compiler options to temporarily enable the TS noUnusedLocal option is a clever way to reuse the TS implementation. It looks like the tslint rule does some additional work on top of what the TS option provides. Wouldn't it make sense to improve the original TS implementation so that there is no need for a temporary program with different compiler options?

**Comment by andy-hanson** [comment]
The TS implementation marks symbols as used while checking them, so it can't be run independently of a `Program`.
The rule still uses the checker to filter out some bogus errors (Microsoft/TypeScript#9944), so still needs to be a `TypedRule`.
The real solution to this problem is to fix Microsoft/TypeScript#9448 and not need a lint rule for this. Same for `--noFallthroughCasesInSwitch` vs `no-switch-case-fall-through`.

**Comment by egamma** [comment]
>The TS implementation marks symbols as used while checking them, so it can't be run independently of a  Program .

Got it, actually not a problem when tslint is run as a language server plugin. In this setup we always pass a Program to tslint [tslint-language-service](https://github.com/angelozerr/tslint-language-service/blob/master/src/index.ts#L217).  

So what I will do for now is to add a setting for the tslint-language-service plugin that allows a user to supress this rule when running as a plugin.

>The real solution to this problem is to fix Microsoft/TypeScript#9448 and not need a lint rule for this. >Same for  --noFallthroughCasesInSwitch  vs  no-switch-case-fall-through .

#9448 has lots of comments, but your point is that you want to have some comment like `// tslint:ignore ...`  for disabling a check for the lint style TS checks. 

Interestingly TS has added a such a comment to disable type checking in JS files with   `// @ts-ignore`, so the time is good to discuss this again.

**Comment by andy-hanson** [comment]
Looks like there is still a TypeScript blug blocking this. The checker tries to grab a `node.symbol` that is undefined. This will have to wait on a solution to Microsoft/TypeScript#15344.

**Comment by adidahiya** [comment]
@ajafff would you be able to take a look here and update the PR as necessary?

**Comment by ajafff** [comment]
I resolved the merge conflicts. The changes regarding case sensitivity from #2819 are still included.

I had to revert the change that created a program consisting of only one source file. That produced exceptions in `getSymbolFlags` while type checking. We now copy all source files.

I verified that it no longer has side effects on other rules by linting https://github.com/CSchulz/tslint-type-check-rule-collision
Note that it took 6 seconds to lint this small sample project. That's caused by copying *every* source file (including declaration files of node_modules) for every linted file.

Re: windows CI failures:
Here's the result of AppVeyor on my branch https://ci.appveyor.com/project/ajafff/tslint/build/1.0.228

**Comment by adidahiya** [comment]
> Note that it took 6 seconds to lint this small sample project

That sounds like a lot. We only take this performance hit when `no-unused-variable` is enabled, right?

**Comment by ajafff** [comment]
> We only take this performance hit when no-unused-variable is enabled, right?

You're right. This might make the rule unusable for larger projects or as a language service plugin, though.

**Comment by egamma** [comment]
>You're right. This might make the rule unusable for larger projects or as a language service plugin, though.

Agreed, when used in language service plugin this will happen as the user types.

**Comment by giladgray** [comment]
@andy-hanson please update this branch so we can review it, or close it if not relevant.

**Comment by johnwiseheart** [comment]
Closing due to age and inactivity. Feel free to re-open or create a new pull request if you decide to continue working on this.

**Pull request closed without merging**
