### PR TITLE
VSCode uses .vscode instead of .settings since 0.8.0

### PR DESCRIPTION
**Pull request by DickvdBrink**
Just moved the files to the new folder (was done automatically by opening it in VSCode)

VSCode seems to changed the line-ending or something... not sure why it changed; can fix it if you want me to :)

### CODE REVIEW

**Comment by adidahiya** [comment]
are you sure it was VSCode that changed the line endings and not git? if it's the former, then that sounds fine

**Comment by DickvdBrink** [comment]
Ah, yeah sorry; It was `git` I guess :)

**Comment by adidahiya** [comment]
Ok, can you please revert the changes to line endings then?

**Comment by DickvdBrink** [comment]
Finally, fixed.. :S

**Comment by adidahiya** [comment]
great, thanks!

**Pull request merged**
