### PR TITLE
[new rule]: ternary-operator-spacing

### PR DESCRIPTION
**Pull request by arhontmw**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [ ] Documentation update

#### Overview of change:
New rule, which determines whether a space is required before and/or after question and colon tokens in ternary conditional operator

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @arhontmw! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by johnwiseheart** [comment]
Hey @arhontmw, is there an issue where this change is discussed? Currently most (if not all) of whitespace linting is done by the `whitespace` rule and it would be good to have a discussion about the pros and cons of separating that rule into several more specific rules. If there is not an issue, feel free to create one.

**Comment by michaeljota** [comment]
Please see #4141 before you contribute to this project. Thank you!

**Comment by JoshuaKGoldberg** [comment]
Per discussion in #4122, and more broadly the upcoming deprecation of TSLint (#4534), closing this issue for housekeeping. @arhontmw you can always publish this rule in a standalone npm package if you'd like to see it used!

**Pull request closed without merging**
