### PR TITLE
new rule no-parameter-reassignment

### PR DESCRIPTION
**Pull request by ajafff**
#### PR checklist

- [x] Addresses an existing issue: #3033
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [x] Documentation update

#### Overview of change:
[new-rule] `no-parameter-reassignment`
Fixes: #3033
/cc @benny-medflyt

### CODE REVIEW

**Comment by benny-medflyt** [comment]
Looks awesome :1st_place_medal: 

I can't quite tell from the code... what did you end up deciding regarding destructured parameters?
I personally think that when this rule is enabled, they should also be affected and prevented from being re-assigned

**Comment by ajafff** [comment]
@benny-medflyt I decided to also check destructured parameters. I don't think it's necessary to add an option to disable that behavior until there is demand for it.

**Comment by ajafff** [comment]
Renamed as suggested and fixed merge conflicts

**Comment by zheeeng** [comment]
I think it is acceptable reassigning params which its type is number, string, boolean. It helps to write some algorithms easy.

**Pull request merged**
