### PR TITLE
Set `esSpecCompliant` for trailing-comma rule in tslint:recommended

### PR DESCRIPTION
**Pull request by chaucerbao**
#### PR checklist

- [x] Addresses an existing issue: #3892 
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### CHANGELOG.md entry:

[rule-change] Set `esSpecCompliant` for [trailing-comma](https://palantir.github.io/tslint/rules/trailing-comma/) rule in *tslint:recommended*

### CODE REVIEW

**Comment by chaucerbao** [comment]
I can't help but feel like the CI failure is not related to this update.

**Comment by david-cannady** [comment]
Yeah same happened to my PR. The issue seems to exist in master. Though, none of the tests failed in my local run.

**Comment by vtambourine** [comment]
Is there any more blockers on this issue? Really want to see it in the nearest build!

**Comment by johnwiseheart** [comment]
@chaucerbao can you confirm whether you have signed the CLA? This should be good to merge.

**Comment by chaucerbao** [comment]
I apologize, I have not gone through the license agreement, not because I don't agree with it, I'm just not comfortable linking my account information to an external app as part of that process.

You (or anyone) are welcome to close this PR and recreate the update. There's no logic, just a preference to be compliant by default.

**Comment by chaucerbao** [comment]
No worries, I understand.

If you also agree that presets should be compliant by default, you can add it internally at Palantir.  Or @vtambourine, if you're up for it you can make a PR.

**Comment by vtambourine** [comment]
@johnwiseheart now I'm confused. Proposed changes is a single line of logicless code, basically a configuration option, already described in TSLint docs that can hardly make any harm. Two comments ago you said `this should be good to merge`. What makes it `unable to take your change` now? What kind of bureaucratic nuance hidden in the CLA that prevents you to accept this change and force someone non-collaborator to sign this agreement?

It also worth to mention, that Palantir made impossible to read CLA before authorizing with personal GitHub account.

**Comment by johnwiseheart** [comment]
Palantir requires that all contributors agree to the terms and conditions in the CLA prior to submitting any contributions. I said this PR was `good to merge` assuming that @chaucerbao had signed the CLA, as the cla-bot has been having some issues of recent and there has been some users who have indeed signed it but it has not updated the status. Because the CLA has not been signed, we cannot accept a contribution from @chaucerbao. 

I agree that it should be possible to view the CLA before authorizing with your account, and will pass that on to the team.

**Comment by vtambourine** [comment]
Thank you for your reply. Can you please clarity two more questions — will
it be possible to other contributors, who signed CLA, to make the same PR?
Is it possible for you, as a maintainers, to implement suggested small, but
relavant and useful feature as regular commits?

**Comment by johnwiseheart** [comment]
Yes, it is possible for other contributors to make the same PR.

Yes, it is possible for me or any of the other maintainers to implement small and useful features. At the moment, most of our time is spent maintaining the project by reviewing PRs and responding to issues rather than developing features. I hope that one day we will have the time to work on new features ourselves too, but as we all have jobs other than maintaining tslint, it is difficult to both develop new features as well as (attempt to) keep the number of PRs and issues low.

**Pull request closed without merging**
