### PR TITLE
Update npm dependencies, fix build on master

### PR DESCRIPTION
**Pull request by adidahiya**
- Fix some NPM warn errors about peerDependencies
- Fix license format (see https://spdx.org/licenses/)

[Review on Reviewable](https://reviewable.io/reviews/palantir/tslint/484)

### CODE REVIEW

**Comment by adidahiya** [comment]
resolves #483

**Comment by leeavital** [comment]
:+1 pending CI

**Comment by leeavital** [comment]
Actually, this might be a good time to add an npm-shrinkwrap.json.

**Comment by adidahiya** [comment]
@leeavital sure, can you add it on top of this commit? pull the `fix-build` branch

**Pull request merged**
