### PR TITLE
Add `no-public-modifiers` rule

### PR DESCRIPTION
**Pull request by mikechamberlain**
#### PR checklist

- [ ] Addresses an existing issue: #0000
- [x] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### What changes did you make?

Added rule to prohibit explicit public modifiers. I prefer a more minimalist approach to code.

#### Is there anything you'd like reviewers to focus on?

(optional)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @mikechamberlain! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by ajafff** [comment]
Can you instead add an option to the existing `member-access` rule to avoid conflicting rules?
The code of both rules seems to be the same anyway.

**Comment by mikechamberlain** [comment]
Hi @ajafff, I'm not sure how this use case could be merged with the existing `member-access` rule. 

Member access is about _requiring_ visibility accessors:

> Requires explicit visibility declarations for class members

But this rule is about _prohibiting_ them (the `public` ones, at least). I can't think of a sane way to add an option into the existing `member-access` rule that would not introduce the possibility of conflict. What do you suggest?

**Comment by mikechamberlain** [comment]
Also, can anyone assist on the failing circleci tests? It's not clear to me from the description what I've done wrong.

**Comment by ajafff** [comment]
CI is failing because of `src/rules/noPublicModifiersRule.ts[41, 6]: Unnecessary semicolon`.
You can run `yarn lint` in your local repository to check this before pushing.


> Member access is about requiring visibility accessors

Well, yes and no. It's about enforcing consistent access modifiers. You're right that right now it requires them everywhere, but that can be changed.

To add this as an option to `member-access` you could add the following at this line: https://github.com/palantir/tslint/blob/master/src/rules/memberAccessRule.ts#L99

```ts
if (this.hasOption('ban-public')) { // option name is for discussion
    if (Lint.hasModifier(node.modifiers, ts.SyntaxKind.PublicKeyword)) {
        this.addFailureAt(...);
    }
    return; // no further checks required
}
```

**Comment by nchen63** [comment]
I agree with @ajafff, this should go in `member-access`. The `ban-public` suggestion sounds good

**Comment by mikechamberlain** [comment]
I agree with everything proposed here. Unfortunately I will have to leave this to someone else as I don't have the inclination to figure it out myself.

**Comment by adidahiya** [comment]
superseded by #2247

**Pull request closed without merging**
