### PR TITLE
pre-commit support

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
#### Overview of change:

Adds a file so that tslint can be used natively with [pre-commit](http://pre-commit.com/). See pre-commit/pre-commit#521 for more discussion.

If this PR is accepted, I'll submit a PR to update the documentation on [pre-commit's side](https://github.com/pre-commit/pre-commit.github.io/blob/real_master/all-repos.yaml).

#### CHANGELOG.md entry:

[enhancement] [pre-commit](http://pre-commit.com/) support

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/tslint/2562)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @alexjurkiewicz! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by alexjurkiewicz** [comment]
There may be some analogous updates from vvakame/typescript-formatter#95 that can be brought into this PR as well (changing language to node and updating the files regex).

**Comment by andy-hanson** [comment]
Generally tslint should be installed from NPM and not from the repository. Binary files aren't checked-in here, but they are published to NPM.

**Comment by adidahiya** [comment]
@alexjurkiewicz can you provide an overview of how this works so that I don't have to comb through the pre-commit documentation? As @andy-hanson noted above, there are no ready-to-go Node.js executables checked in here on Github.

**Comment by alexjurkiewicz** [comment]
Quick description of `pre-commit`: `pre-commit` is a tool that runs different scripts (linters, formatters, etc) on your files-to-be-committed based on their file extension, giving a quick pass/fail for simple code quality tests / other uses. The addition of a `.pre-commit-hooks.yaml` file to this repo allows pre-commit users to use tslint with an official configuration (eg no dependence on third party repo). Here's an example terminal session:

```
$ cat .pre-commit-config.yaml
# If this PR is changed, the contents would change to refer to the official tslint repository
- repo: local
  hooks:
  - id: tslint
    name: tslint
    entry: tslint
    files: \.tsx?$
    language: node

$ pre-commit install
pre-commit installed at /home/aj/tsrl/.git/hooks/pre-commit

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   src/entity-list.ts

$ git commit
tslint...................................................................Failed
hookid: tslint

ERROR: src/entity-list.ts[11, 5]: Calls to 'console.log' are not allowed.
ERROR: src/entity-list.ts[12, 5]: Calls to 'console.log' are not allowed.

$
```

> Generally tslint should be installed from NPM and not from the repository. Runnable .js files aren't checked-in here, but they are published to NPM.

This PR isn't quite correct, but the idea is `pre-commit` will create an empty temp directory, run `npm install tslint` and then `tslint modified/file.ts`. So there doesn't need to be anything in this repository except `.pre-commit-hooks.yaml` file and `package.json`. You could create a blank stub repo like [jshint](https://github.com/pre-commit/mirrors-jshint) instead. The value in putting the file in this repo is conceptual simplicity for users (refer to the official tslint repo to use tslint).

**Comment by adidahiya** [comment]
Can pre-commit users pin to a specific version of TSLint or does it always use the HEAD of the default branch?

**Comment by alexjurkiewicz** [comment]
The SHA key in the above snippet pins to a specific version of this repo's pre commit hooks file. If the file is periodically updated with the latest version of tslint as an additional dependency, users can pick a sha with the desired tslint version.

Technically, you can also use a tag. So if you release tslint v13, before you tag the repo with v13, just update the pre commit file. Then users can specify this repo@v13 to get their desired version.

**Pull request closed without merging**
