### PR TITLE
[WIP] feat: Add ignored-clause in cyclomatic-complexity rule

### LINKED ISSUE #4436: Enable/Disable switch cases from the cyclomatic complexity rule
### Enable/Disable switch cases from the cyclomatic complexity rule

It would be great to be able to disable switches from being taken into account for cyclomatic complexity, specially

Imagine the following: you have to render an icon depending on a status prop on a pure function. This piece of code can render up to as many icons as the application requires for it's component statuses. 

```
switch(this.status) {
 case State.Idle:
        return <IdleIcon />
 case State.Active:
        return <ActiveIcon/>
 (...)
 case State.Deleted:
        return <DeletedIcon/>
}
```

You're now left with a couple of options:

* Create helper functions to satisfy the linter (i.e `this.renderActiveOrIdle`, pretty annoying)
* Add a disabler comment to workaround the linter
* Keep increasing the cyclomatic complexity threshold each time this issue pops up

I think these kind of switches are really easy to visualize. That said, I understand that more complex switches could be the reason to negate the request. Maybe adding a character threshold or line threshold between cases could suffice?

We have the threshold at 6 and it is often the case that we add the disabler comment (though we only allow it for switches).

At least in our case we tend to use switches for quick conditionals only, such as the case above. Any chance this could be a feature in the future?

### PR DESCRIPTION
**Pull request by mouadennaciri**
#### PR checklist

- [x] Addresses an existing issue: fixes #4436
- [x] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Overview of change:
See #4489

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @mouadennaciri! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by JoshuaKGoldberg** [comment]
👋 ping @mouadennaciri do you plan on finishing this PR? It'd be great to have the new rule option in!

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests other than for security fixes. See #4534. ☠️ 

If you'd like to see this feature implemented, you have two choices:
* **Recommended:** Use [typescript-eslint](https://typescript-eslint.io) to lint your TypeScript code with ESLint ✅
* **Legacy:** Fork TSLint and use a version with this feature 🤷‍♂️

👋 It was a pleasure open sourcing with you!

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests other than security fixes. See #4534. ☠️ 

If you'd like to see this feature implemented, you have two choices:
* **Recommended:** Use [typescript-eslint](https://typescript-eslint.io) to lint your TypeScript code with ESLint ✅
* **Not Recommended:** Fork TSLint and add this feature in the forked version 🤷‍♂️

👋 It was a pleasure open sourcing with you!

**Pull request closed without merging**
