### PR TITLE
small cleanup

### PR DESCRIPTION
**Pull request by ashwinr**
- redirect bin verification output to /dev/null
- remove unnecessary rule disabling comments
- remove strange swp file

### CODE REVIEW

**Comment by adidahiya** [comment]
:+1:

**Comment by adidahiya** [comment]
I'll rebase & force push this commit

**Comment by adidahiya** [comment]
@leeavital can you investigate what's going on here? are either of the builds flakes? does travis CI not support something we're trying to do with shell redirection?

**Comment by leeavital** [comment]
@adidahiya I'm going to rebase on #462 before looking to into this.

**Comment by impinball** [comment]
The Travis CI test implies the [sanity check on the binary is failing](https://travis-ci.org/palantir/tslint/builds/68189623#L597-L613). It's complaining about a missing required `-f` option.

**Pull request closed without merging**
