### PR TITLE
Prepare release 5.8.1

### PR DESCRIPTION
**Pull request by dradetsky**
#### PR checklist
n/a

#### Overview of change:
attempting to cut a new release, since recent changes close issues for us

#### Is there anything you'd like reviewers to focus on?
i dunno; whether i did semver right?

also, the output of the changelog script wasn't similar to recent entries, so i cut/pasted by hand. I may have done it wrong.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @dradetsky! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by ajafff** [comment]
> i dunno; whether i did semver right?

It's actually 5.9.0 since there are not only bug fixes.

> also, the output of the changelog script wasn't similar to recent entries, so i cut/pasted by hand. I may have done it wrong.

Unfortunately the script only works if the PR contains the relevant information. Otherwise this needs to be done by hand. But the script outputs the relevant commits that are missing docs.
By looking at the changelog, I think there are some entries missing. For example the added support for YAML configs.

**Comment by dradetsky** [comment]
@ajafff does that mean I have to manually add entries to the changelog for the missing stuff?

**Comment by dradetsky** [comment]
also, i'll make a new branch with 5.9.0 if this is otherwise ok (or if the other req'd changes are not too much trouble)

**Comment by ajafff** [comment]
> does that mean I have to manually add entries to the changelog for the missing stuff?

Yep. That's a pretty tedious task. The changelog script spits out a list of commits that don't have docs, you copy the PR number from the commit message, lookup the PR and add n changelog entries.
After that you add headlines and group the entries like you already did. In all previous releases Adi Dahiya and Jason Killian were not in the list of contributors as they are basically the owners of this project.

It would be great if you want to do this. You don't necessarily need a new branch, you can just override the changes in this branch.

**Comment by dradetsky** [comment]
it's just that I did this release because it's a problem for something we're trying to do now, so the simplest solution probably isn't doing a release. but maybe soon

**Comment by adidahiya** [comment]
closing this in favor of a 5.9.0 I'll cut this week

**Pull request closed without merging**
